#!/bin/bash
set -e

# Colors for terminal styling
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "=================================================="
echo "      🛡️ AI CODE GUARDIAN - SETUP WIZARD 🛡️      "
echo "=================================================="
echo -e "${NC}"
echo "This wizard will install the AI Code Guardian GitHub Action"
echo "and configuration file into your target repository."
echo ""

# 1. Ask for target repository path
read -p "📁 Enter the absolute or relative path to your target project folder (e.g., ../my-project or .): " TARGET_DIR

# Check if directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${RED}Error: Directory '$TARGET_DIR' does not exist.${NC}"
    exit 1
fi

# Ensure it's a git repository (optional but good practice)
if [ ! -d "$TARGET_DIR/.git" ]; then
    echo -e "${YELLOW}Warning: '$TARGET_DIR' does not appear to be a Git repository.${NC}"
    read -p "Do you want to continue anyway? (y/N): " FORCE_GIT
    if [[ ! "$FORCE_GIT" =~ ^[Yy]$ ]]; then
        echo "Setup aborted."
        exit 1
    fi
fi

echo ""
echo -e "${BLUE}--- Configuration Options ---${NC}"

# 2. Ask for features
read -p "🔐 Enable Security Vulnerability Scanning? (Y/n): " ENABLE_SECURITY
ENABLE_SECURITY=${ENABLE_SECURITY:-Y}

read -p "✋ Block PR merges if CRITICAL security issues are found? (Y/n): " BLOCK_CRITICAL
BLOCK_CRITICAL=${BLOCK_CRITICAL:-Y}

read -p "📊 Enable Code Quality & Smell Analysis (Beta)? (y/N): " ENABLE_QUALITY
ENABLE_QUALITY=${ENABLE_QUALITY:-N}

read -p "🏗️ Enable Code Practices & Architecture Enforcement? (y/N): " ENABLE_PRACTICES
ENABLE_PRACTICES=${ENABLE_PRACTICES:-N}

# 3. Process answers
if [[ "$BLOCK_CRITICAL" =~ ^[Yy]$ ]]; then
    BLOCK_ON_SEVERITY="    - ERROR"
    ACTION_BLOCK="\"true\""
else
    BLOCK_ON_SEVERITY="    # - ERROR"
    ACTION_BLOCK="\"false\""
fi

if [[ "$ENABLE_SECURITY" =~ ^[Yy]$ ]]; then CFG_SEC="true"; else CFG_SEC="false"; fi
if [[ "$ENABLE_QUALITY" =~ ^[Yy]$ ]]; then CFG_QUAL="true"; else CFG_QUAL="false"; fi
if [[ "$ENABLE_PRACTICES" =~ ^[Yy]$ ]]; then CFG_PRAC="true"; else CFG_PRAC="false"; fi

echo ""
echo -e "${BLUE}--- Generating Files ---${NC}"

# 4. Create .ai-guardian.yml
CONFIG_FILE="$TARGET_DIR/.ai-guardian.yml"
echo "Writing configuration to $CONFIG_FILE..."

cat <<EOF > "$CONFIG_FILE"
# AI Code Guardian Configuration
# Generated by AI Code Guardian Setup Wizard

security:
  enabled: ${CFG_SEC}
  block_on_severity:
${BLOCK_ON_SEVERITY}

quality:
  enabled: ${CFG_QUAL}

practices:
  enabled: ${CFG_PRAC}

exclude:
  - "tests/"
  - "node_modules/"
  - ".git/"
EOF

# 5. Create GitHub Action Workflow
WORKFLOW_DIR="$TARGET_DIR/.github/workflows"
WORKFLOW_FILE="$WORKFLOW_DIR/ai-code-guardian.yml"

echo "Creating GitHub Actions directory at $WORKFLOW_DIR..."
mkdir -p "$WORKFLOW_DIR"

echo "Writing GitHub Action workflow to $WORKFLOW_FILE..."

cat <<EOF > "$WORKFLOW_FILE"
name: AI Code Guardian

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release

permissions:
  contents: read
  pull-requests: write

jobs:
  code-guardian-scan:
    name: AI Code Guardian Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run AI Code Guardian
        uses: abin-g/ai-code-guardian-action@v1
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          block_on_findings: ${ACTION_BLOCK}
EOF

echo ""
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "AI Code Guardian has been successfully integrated into:"
echo "  -> $TARGET_DIR"
echo ""
echo "Next steps:"
echo "1. cd $TARGET_DIR"
echo "2. git add .ai-guardian.yml .github/workflows/ai-code-guardian.yml"
echo "3. git commit -m 'chore: integrate AI Code Guardian'"
echo "4. git push"
echo ""
echo "Your PRs will now be automatically scanned. Happy secure coding! 🚀"
