#!/bin/bash
set -e

# Colors for terminal styling
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "=================================================="
echo "      🛡️ SENTINEL CI - SETUP WIZARD 🛡️      "
echo "=================================================="
echo -e "${NC}"
echo "This wizard will install Sentinel CI (AI Code Guardian engine) for GitHub Actions"
echo "and configuration file into your target repository."
echo ""

# 1. Ask for target repository path
read -p "📁 Enter the absolute or relative path to your target project folder (e.g., ../my-project or .): " TARGET_DIR

# Check if directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${RED}Error: Directory '$TARGET_DIR' does not exist.${NC}"
    exit 1
fi

# Ensure it's a git repository (optional but good practice)
if [ ! -d "$TARGET_DIR/.git" ]; then
    echo -e "${YELLOW}Warning: '$TARGET_DIR' does not appear to be a Git repository.${NC}"
    read -p "Do you want to continue anyway? (y/N): " FORCE_GIT
    if [[ ! "$FORCE_GIT" =~ ^[Yy]$ ]]; then
        echo "Setup aborted."
        exit 1
    fi
fi

echo ""
echo -e "${BLUE}--- Configuration Options ---${NC}"

# 2. Ask for features
read -p "🔐 Enable Security Vulnerability Scanning? (Y/n): " ENABLE_SECURITY
ENABLE_SECURITY=${ENABLE_SECURITY:-Y}

read -p "✋ Block PR merges on strict security policy (ERROR + WARNING)? (Y/n): " BLOCK_STRICT
BLOCK_STRICT=${BLOCK_STRICT:-Y}

read -p "📊 Enable Code Quality & Smell Analysis (Beta)? (Y/n): " ENABLE_QUALITY
ENABLE_QUALITY=${ENABLE_QUALITY:-Y}

read -p "🏗️ Enable Code Practices & Architecture Enforcement? (Y/n): " ENABLE_PRACTICES
ENABLE_PRACTICES=${ENABLE_PRACTICES:-Y}

# 2.5 Ask for the main production branch (base branch for PR events)
read -p "🌿 Enter your main production branch name (base branch for PRs, e.g., 'main'): " PROD_BRANCH
PROD_BRANCH=${PROD_BRANCH:-main}

# 3. Process answers
if [[ "$BLOCK_STRICT" =~ ^[Yy]$ ]]; then
    # Strict mode: block merge for both ERROR and WARNING security findings.
    BLOCK_ON_SEVERITY="    - ERROR\n    - WARNING"
    ACTION_BLOCK="\"true\""
else
    # Conservative mode: only block merge on ERROR.
    BLOCK_ON_SEVERITY="    - ERROR\n    # - WARNING"
    ACTION_BLOCK="\"true\""
fi

if [[ "$ENABLE_SECURITY" =~ ^[Yy]$ ]]; then CFG_SEC="true"; else CFG_SEC="false"; fi
if [[ "$ENABLE_QUALITY" =~ ^[Yy]$ ]]; then CFG_QUAL="true"; else CFG_QUAL="false"; fi
if [[ "$ENABLE_PRACTICES" =~ ^[Yy]$ ]]; then CFG_PRAC="true"; else CFG_PRAC="false"; fi

echo ""
echo -e "${BLUE}--- Generating Files ---${NC}"

# 4. Create .sentinel-ci.yml
CONFIG_FILE="$TARGET_DIR/.sentinel-ci.yml"
echo "Writing configuration to $CONFIG_FILE..."

cat <<EOF > "$CONFIG_FILE"
# Sentinel CI policy (.sentinel-ci.yml — AI Code Guardian engine)
# Generated by Sentinel CI Setup Wizard

security:
  enabled: ${CFG_SEC}
  block_on_severity:
${BLOCK_ON_SEVERITY}

quality:
  enabled: ${CFG_QUAL}

practices:
  enabled: ${CFG_PRAC}
  guidelines:
    - "Avoid direct use of eval or Function constructor."
    - "Do not keep business logic directly inside route page files."
    - "Use strong password hashing (bcrypt/argon2), never md5/sha1 for passwords."
    - "Keep components small and move reusable logic into shared modules."

exclude:
  - "tests/"
  - "node_modules/"
  - ".git/"
EOF

# 5. Create GitHub Action Workflow
WORKFLOW_DIR="$TARGET_DIR/.github/workflows"
WORKFLOW_FILE="$WORKFLOW_DIR/sentinel-ci.yml"

echo "Creating GitHub Actions directory at $WORKFLOW_DIR..."
mkdir -p "$WORKFLOW_DIR"

echo "Writing GitHub Action workflow to $WORKFLOW_FILE..."

cat <<EOF > "$WORKFLOW_FILE"
name: Sentinel CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ${PROD_BRANCH}

permissions:
  contents: read
  pull-requests: write

jobs:
  sentinel-ci-scan:
    name: Sentinel CI Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Sentinel CI
        uses: abin-g/sentinel-ci-action@v1
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          block_on_findings: ${ACTION_BLOCK}
EOF

echo ""
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "Sentinel CI has been successfully integrated into:"
echo "  -> $TARGET_DIR"
echo ""
echo "Next steps:"
echo "1. cd $TARGET_DIR"
echo "2. git add .sentinel-ci.yml .github/workflows/sentinel-ci.yml"
echo "3. git commit -m 'chore: integrate Sentinel CI'"
echo "4. git push"
echo ""
echo "Your PRs will now be automatically scanned. Happy secure coding! 🚀"

# Remove this setup wizard file from the local machine after successful completion.
# We only delete when the script file itself is named `setup.sh` to avoid surprises.
SCRIPT_TO_DELETE_SRC="${BASH_SOURCE[0]}"
# Resolve to an absolute path so cleanup works reliably even if the script was invoked from another directory.
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_TO_DELETE_SRC")" && pwd)"
SCRIPT_TO_DELETE="${SCRIPT_DIR}/$(basename "$SCRIPT_TO_DELETE_SRC")"
if [[ -f "$SCRIPT_TO_DELETE" && "$(basename "$SCRIPT_TO_DELETE")" == "setup.sh" ]]; then
  echo -e "${YELLOW}Cleaning up: removing $SCRIPT_TO_DELETE${NC}"
  rm -f "$SCRIPT_TO_DELETE" || true
fi
